# Generated by Django 3.1.6 on 2021-02-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='name_text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='question',
        ),
        migrations.RemoveField(
            model_name='user',
            name='question_text',
        ),
    ]
