# Generated by Django 3.1.6 on 2021-04-22 05:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='untitled course', max_length=25)),
                ('color', models.CharField(default='#F6F6F6', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Todolist', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks_created', models.IntegerField(default=0)),
                ('total_courses_created', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('description_text', models.CharField(default='Untitled Task', max_length=200)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Due Date')),
                ('time_estimate', models.IntegerField(default=0)),
                ('initial_subtask_count', models.IntegerField(default=0)),
                ('is_subtask', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='pages.course')),
                ('parent_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='pages.task')),
                ('todo_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.todolist')),
            ],
        ),
    ]
