# Generated by Django 3.1.7 on 2021-03-15 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField()),
                ('description_text', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('time_estimate', models.IntegerField(default=0)),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.todolist')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
