# Generated by Django 3.1.7 on 2021-03-17 17:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_websitemeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='untitled course', max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='todolist',
            new_name='todo_list',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
        migrations.AddField(
            model_name='websitemeta',
            name='total_courses_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='description_text',
            field=models.CharField(default='Untitled Task', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(default='Untitled Todolist', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='pages.course'),
        ),
    ]
