# Generated by Django 3.1.7 on 2021-03-17 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210317_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='todo_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.todolist'),
        ),
    ]
