# Generated by Django 3.1.7 on 2021-04-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_subtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='todo_list',
            new_name='task',
        ),
        migrations.AddField(
            model_name='subtask',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
