# Generated by Django 3.1.6 on 2021-05-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210507_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='courses',
            field=models.ManyToManyField(to='pages.Course'),
        ),
    ]
