# Generated by Django 3.1.7 on 2021-04-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210409_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='empty_field',
        ),
        migrations.AddField(
            model_name='subtask',
            name='is_subtask',
            field=models.BooleanField(default=True),
        ),
    ]
