# Generated by Django 3.1.7 on 2021-04-09 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20210409_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='test2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task2', to='pages.task'),
        ),
    ]
