# Generated by Django 3.1.7 on 2021-04-09 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_subtask_test2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='test2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test3', to='pages.task'),
        ),
    ]
