# Generated by Django 3.1.7 on 2021-04-09 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20210409_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_subtask',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask_parent', to='pages.task'),
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
