# Generated by Django 3.1.7 on 2021-04-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210409_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='initial_subtask_count',
            field=models.IntegerField(default=0),
        ),
    ]
